export const API_URL = '';

export const STATUS_SUCCESS = 'success';
export const STATUS_ERROR = 'error';
export const SUBMITTING = 'SUBMITTING';
export const SUBMITTED = 'SUBMITTED';

export const REGISTER_INITIAL = 'REGISTER_INITIAL';
export const REGISTER_GET_ALL_DAYAH = 'REGISTER_GET_ALL_DAYAH';
export const REGISTER_SUBMITTING = 'REGISTER_SUBMITTING';
export const REGISTER_SUBMITTED = 'REGISTER_SUBMITTED';

export const LOGIN_INITIAL = 'LOGIN_INITIAL';
export const LOGIN_GET_ALL_DAYAH = 'LOGIN_GET_ALL_DAYAH';
export const LOGIN_SUBMITTING = 'LOGIN_SUBMITTING';
export const LOGIN_SUBMITTED = 'LOGIN_SUBMITTED';